Repository DeepRegNet/DeepReg, pull requests merged in 2020-11, with the labels that each got.

#506 Issue #505: Updated to correct stable tag for PyPI releases
  setup.py
Labels: bug

#518 Issue #502: Post-release / post-JOSS README.md update
  CHANGELOG.md
  README.md
Labels: docs

#522 Issue #408: Add checkout, build and release workflow
  .github/workflows/python-publish.yml
  setup.py
Labels: config, feature

#520 496 minor typos in docs
  docs/source/tutorial/registration.md
Labels: typo

#541 Issue #540: Add downloads badge, organize all badges
  README.md
Labels: docs
