Repository DeepRegNet/DeepReg, pull requests merged in 2020-08, with the labels that each got.

#260 Simplifying README.md
  README.md
Labels: documentation

#249 12 label reg
  demos/paired_mrus_prostate/README.md
  demos/paired_mrus_prostate/demo_data.py
  demos/paired_mrus_prostate/demo_predict.py
  demos/paired_mrus_prostate/demo_train.py
  demos/paired_mrus_prostate/paired_mrus_prostate_dataset0.yaml
  demos/paired_mrus_prostate/paired_mrus_prostate_train.yaml
Labels: demo

#264 [WIP] 1 joss new
  .prettierignore
  docs/home.md
  docs/joss_paper/paper.bib
  docs/joss_paper/paper.md
Labels: documentation

#334 291 pypi release
  README.md
  deepreg/config/__init__.py
  deepreg/config/test/__init__.py
  deepreg/model/backbone/__init__.py
  deepreg/model/loss/__init__.py
  docs/source/contributing/build.md
  docs/source/getting_started/install.rst
  docs/source/index.rst
  setup.cfg
  setup.py
Labels: documentation, enhancement
