Repository DeepRegNet/DeepReg, pull requests merged in 2020-07, with the labels that each got.

#150 114 on the fly resizing
  deepreg/config/paired_labeled_global_ddf.yaml
  deepreg/config/test/grouped_h5.yaml
  deepreg/config/test/grouped_nifti.yaml
  deepreg/config/test/paired_h5.yaml
  deepreg/config/test/paired_nifti.yaml
  deepreg/config/test/unpaired_h5.yaml
  deepreg/config/test/unpaired_nifti.yaml
  deepreg/config/test/unpaired_nifti_multi_dirs.yaml
  deepreg/config/test/unpaired_nifti_no_valid.yaml
  deepreg/config/unpaired_labeled_ddf.yaml
  deepreg/dataset/loader/interface.py
  deepreg/dataset/preprocess.py
  deepreg/model/layer.py
  deepreg/model/layer_util.py
  deepreg/model/network/cond.py
  deepreg/model/network/ddf_dvf.py
  docs/doc_data_loader.md
  test/unit/test_layer_util.py
  test/unit/test_network_cond.py
  test/unit/test_network_ddf_dvf.py
  test/unit/test_preprocess_resize.py
Labels: enhancement

#208 207 update readme
  README.md
  deepreg_logo_purple_beta.svg
  docs/home.md
Labels: documentation

#209 Issue #55: Improve coverage for layer_utils.py
  deepreg/model/layer_util.py
  test/unit/test_layer_util.py
Labels: enhancement, tests

#219 161 - Adding CME logo
  README.md
  docs/asset/medicalengineering.svg
  docs/home.md
Labels: enhancement

#241 210 Update badge links for Travis
  README.md
Labels: bug, documentation
