Repository DeepRegNet/DeepReg, pull requests merged in 2021-01, with the labels that each got.

#618 617 refactoring of data augmentation
  .gitignore
  CHANGELOG.md
  config/test/ddf.yaml
  config/unpaired_labeled_ddf.yaml
  deepreg/dataset/__init__.py
  deepreg/dataset/loader/interface.py
  deepreg/dataset/preprocess.py
  deepreg/model/layer_util.py
  demos/classical_ct_headneck_affine/demo_register.py
  demos/grouped_mask_prostate_longitudinal/grouped_mask_prostate_longitudinal.yaml
  demos/grouped_mr_heart/grouped_mr_heart.yaml
  demos/paired_ct_lung/paired_ct_lung.yaml
  demos/paired_mrus_brain/paired_mrus_brain.yaml
  demos/paired_mrus_prostate/paired_mrus_prostate.yaml
  demos/unpaired_ct_abdomen/unpaired_ct_abdomen_comb.yaml
  demos/unpaired_ct_abdomen/unpaired_ct_abdomen_unsup.yaml
  demos/unpaired_ct_abdomen/unpaired_ct_abdomen_weakly.yaml
  demos/unpaired_ct_lung/unpaired_ct_lung.yaml
  demos/unpaired_mr_brain/unpaired_mr_brain.yaml
  demos/unpaired_us_prostate_cv/unpaired_us_prostate_cv.yaml
  test/unit/test_interface.py
  test/unit/test_layer_util.py
  test/unit/test_preprocess.py
  test/unit/test_util.py
Labels: priority

#616 Issue #615: add zero boundary option to resampler and set as default
  CHANGELOG.md
  deepreg/model/layer_util.py
  deepreg/warp.py
  test/unit/test_layer_util.py
  test/unit/test_util.py
Labels: priority

#559 525: update config file docs
  CHANGELOG.md
  docs/source/docs/configuration.md
Labels: config, docs

#659 Issue #657 changelog updated for r012
  CHANGELOG.md
Labels: docs
